-- AlterEnum
ALTER TYPE "LeadSource" ADD VALUE 'MAGICBRICKS';
ALTER TYPE "LeadSource" ADD VALUE 'INDIAMART';
ALTER TYPE "LeadSource" ADD VALUE 'QR_CODE';
ALTER TYPE "LeadSource" ADD VALUE 'REFERRAL';
ALTER TYPE "LeadSource" ADD VALUE 'YOUTUBE';
ALTER TYPE "LeadSource" ADD VALUE 'JUST_DIAL';
