name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-api:
    name: API — typecheck & build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci --legacy-peer-deps
        working-directory: .
      - run: npx tsc --noEmit
      - run: npx nest build

  check-web:
    name: Web — typecheck & build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    env:
      NEXT_PUBLIC_API_URL: http://localhost:4000/api/v1
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci --legacy-peer-deps
        working-directory: .
      - run: npx tsc --noEmit
      - run: npm run build
